# Generated by Django 3.1.2 on 2020-10-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=60)),
                ('fecha_subida', models.DateField()),
                ('estado', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateField()),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField()),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apialumnos.usuario')),
                ('legajo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'ordering': ['legajo'],
            },
            bases=('apialumnos.usuario',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apialumnos.usuario')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
            },
            bases=('apialumnos.usuario',),
        ),
        migrations.CreateModel(
            name='ArchivoHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nuevo_estado', models.CharField(max_length=60)),
                ('archivo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apialumnos.archivo')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apialumnos.usuario')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apialumnos.usuario'),
        ),
    ]
